<?php

namespace Ipc\ProgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
    public function myFindCourant()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
        	->select('s')
            ->from($this->_entityName,'s')
            ->where('s.siteCourant = :courant')
            ->setParameter('courant',true);
        $query = $queryBuilder->getQuery();
        try {
            $result = $query ->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $result = null;
        }
        return $result;
    }

	public function myFindOneByParametreLike($parametre) {
		$parametre = $parametre.'%';
		$qb = $this->createQueryBuilder('c');
		$qb->where($qb->expr()->like('c.parametre',':parametre'))
			->setParameter('parametre', $parametre);
		try {
            $result = $qb->getQuery()->getArrayResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $result = null;
        }
        return $result;
	}


	public function getValueOf($parametre){
		$qb = $this->createQueryBuilder('c');
		$qb->select('c.valeur')
		->where('c.parametre = :parametre')
		->setParameter('parametre', $parametre);
		return $qb->getQuery()->getSingleScalarResult();
	}

	public function myGetSqlValueOf($dbh, $database, $parametre) {
		$retour_valeur_nb_jours = -1;
		$requete = "SELECT valeur FROM $database.t_configuration WHERE parametre = '$parametre'";
        if (($response = $dbh->query($requete)) != false) {
        	$retour_valeur_nb_jours = $response->fetchColumn();
           	$response->closeCursor();
        }
        return($retour_valeur_nb_jours);
	}
}
