imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

fos_user:
    db_driver:     orm
    firewall_name: main
    # Renseigne la nouvelle entité Utilisateur
    user_class:    Ipc\UserBundle\Entity\User
    # Renseigne le nouveau formulaire d'inscription
    registration:
        form:
            type: ipc_user_registration
        # Validation automatique du compte par envoi d'email
        confirmation:
            enabled: false
            from_email:
                 # Adresse de l'expediteur
                 address: 'Admin_ipc@cargo-france.fr'
                 # Nom de l'expediteur
                 sender_name: 'Administrateur Ipc'
framework:
    esi:            { enabled: true }
    fragments: 		{ path: /_fragment }
    translator:     { fallback: "%locale%" }
    secret:         "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%secret%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        # maxlifetime défini à 30 minutes d'inactivité
        cookie_lifetime: ~
        gc_maxlifetime: 1800
        gc_probability: 3
        gc_divisor: 4
        handler_id:  ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        service_js_traductions: "@ipc_prog.traduction"
        service_session: "@ipc_prog.session"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ IpcUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp: 
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        optipng:
            apply_to: "\.png$"
            level: 3
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
            #apply_to: "\.css$"
    twig:
        functions:
            optipng: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: "%kernel.root_dir%/data/data.db3"
                # path:     "%database_path%"
            boilerbox:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_m168:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_m168"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c782:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c782"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c671:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c671"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c856:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c856"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c852:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c852"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c658:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c658"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c811:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c811"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c860:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c860"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c820:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c820"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c917:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c917"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
            boilerbox_c874:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_c874"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                unix_socket: "%socket_unix%"
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                #/auto_generate_proxy_classes: "%kernel.debug%"
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox:
                connection: boilerbox
                mappings:
                    LciBoilerBoxBundle: ~
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_m168:
                connection: boilerbox_m168
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c782:
                connection: boilerbox_c782
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c671:
                connection: boilerbox_c671
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c856:
                connection: boilerbox_c856
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c852:
                connection: boilerbox_c852
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c658:
                connection: boilerbox_c658
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c811:
                connection: boilerbox_c811
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c860:
                connection: boilerbox_c860
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c820:
                connection: boilerbox_c820
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c917:
                connection: boilerbox_c917
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~
            boilerbox_c874:
                connection: boilerbox_c874
                mappings:
                    FOSUserBundle: ~
                    IpcProgBundle: ~
                    IpcUserBundle: ~
                    IpcConfigurationBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode: "%mailer_auth%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    #delivery_address: "%mailer_delivery%"
    disable_delivery: "%mailer_disable%"
    sender_address: "%mailer_sender%"
    spool: 
               type: file
               path: "%kernel.root_dir%/spool"
